[phases.setup]
nixPkgs = ["php82", "php82Extensions.gd", "php82Extensions.zip", "composer"]

[phases.build]
cmds = ["composer install --no-interaction --prefer-dist"]

[phases.start]
cmd = "php -S 0.0.0.0:$PORT -t public"
